// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKhn02RsHJ39G8cbuaR7G2Gs-7azgTzw',
    appId: '1:403798651303:web:3022ed089dffce48394682',
    messagingSenderId: '403798651303',
    projectId: 'fcm-practice-b0b87',
    authDomain: 'fcm-practice-b0b87.firebaseapp.com',
    storageBucket: 'fcm-practice-b0b87.appspot.com',
    measurementId: 'G-CFHEMNQ012',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf5lZcwZtSYFQF8Y4NNEWpbx6s15ekPV8',
    appId: '1:403798651303:android:443594dc792a65c3394682',
    messagingSenderId: '403798651303',
    projectId: 'fcm-practice-b0b87',
    storageBucket: 'fcm-practice-b0b87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44x1McGzWN84-phvBju14nnrowIs36ww',
    appId: '1:403798651303:ios:e94b712d242fa1b5394682',
    messagingSenderId: '403798651303',
    projectId: 'fcm-practice-b0b87',
    storageBucket: 'fcm-practice-b0b87.appspot.com',
    iosClientId: '403798651303-ssto0gjoilmfmdsp48rvidcnugj4gaqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.firebase-cloud-messeging',
  );
}
